--PAQUETE de Busqueda de centros de trabajo
--CABECERA DEL PAQUETE
CREATE OR REPLACE PACKAGE PAQUETE_BUSCAR_CT IS
PROCEDURE BUSCAR_TOTAL_CT (B OUT SYS_REFCURSOR);
END;
 
--CUERPO DEL PAQUETE
CREATE OR REPLACE PACKAGE BODY PAQUETE_BUSCAR_CT IS
PROCEDURE BUSCAR_TOTAL_CT(B OUT SYS_REFCURSOR)
IS
BEGIN
OPEN B FOR
SELECT *  FROM TCENTRO_TRABAJO;
END;
END;

--PAQUETE de Busqueda de un Centro de trabajo concreto
--CABECERA DEL PAQUETE
CREATE OR REPLACE PACKAGE PAQUETE_BUSCAR_UN_CT IS
PROCEDURE BUSCAR_UN_CENTRO ( ID_C IN TCENTRO_TRABAJO.ID_CENTRO%TYPE, B OUT SYS_REFCURSOR);
END;
 
--CUERPO DEL PAQUETE
CREATE OR REPLACE PACKAGE BODY PAQUETE_BUSCAR_UN_CT IS
PROCEDURE BUSCAR_UN_CENTRO ( ID_C IN TCENTRO_TRABAJO.ID_CENTRO%TYPE, B OUT SYS_REFCURSOR)
IS
BEGIN
OPEN B FOR
  SELECT * FROM TCENTRO_TRABAJO 
  WHERE ID_CENTRO = ID_C;
  EXCEPTION 
  WHEN NO_DATA_FOUND THEN
  RAISE_APPLICATION_ERROR( -20000  , 'Error', TRUE);
  WHEN TOO_MANY_ROWS THEN
  RAISE_APPLICATION_ERROR( -20000  , 'Error', TRUE);
END;
END;

--Procedimiento de Busqueda de todos los Trabajadores
CREATE OR REPLACE PROCEDURE BUSCAR_TOTAL_T (B OUT SYS_REFCURSOR)
IS
BEGIN
  OPEN B FOR
  SELECT * FROM TTRABAJADOR;
END;

--Procedimiento de Busqueda de un Trabajador
CREATE OR REPLACE PROCEDURE BUSCAR_UN_T (ID_T IN INTEGER, B OUT SYS_REFCURSOR)
AS
BEGIN
OPEN B FOR
  SELECT *  FROM TTRABAJADOR
  WHERE ID_TRABAJADOR = ID_T;
  EXCEPTION 
  WHEN NO_DATA_FOUND THEN
  RAISE_APPLICATION_ERROR( -20000  , 'Error', TRUE);
  WHEN TOO_MANY_ROWS THEN
  RAISE_APPLICATION_ERROR( -20000 , 'Error', TRUE);
END;

--Procedimiento de comprobación del login de usuario
create or replace PROCEDURE COMPROBAR_LOGIN (USU IN VARCHAR2 , PASS IN VARCHAR2, V OUT number )
AS
LINEA TCLAVE%ROWTYPE;
BEGIN
  SELECT * INTO LINEA FROM TCLAVE
  WHERE USU = TCLAVE.USUARIO
  and TCLAVE.CONTRASENA = PASS;
  IF LINEA.USUARIO = USU THEN
  V:= linea.trabajador_id_trabajador;
  END IF;
  EXCEPTION
      WHEN NO_DATA_FOUND THEN
      v:=0;
END;

--Creación de las secuencias usadas para los ID de algunas tablas.
CREATE SEQUENCE ID_CENTRO 
  INCREMENT BY 10 START WITH 10 
  NOMAXVALUE
  MINVALUE 10;
  
  CREATE SEQUENCE ID_TRABAJADOR 
  INCREMENT BY 1 START WITH 1 
  NOMAXVALUE
  MINVALUE 1;
  
  CREATE SEQUENCE ID_CLAVE 
  INCREMENT BY 1 START WITH 1 
  NOMAXVALUE
  MINVALUE 1;
  
 

--DROP PUBLIC SYNONYM CONSULTA_CT FOR PAQUETE_BUSCAR_CT ;
--DROP PUBLIC SYNONYM CONSULTA_UN_CT FOR PAQUETE_BUSCAR_UN_CT;
--DROP PUBLIC SYNONYM CONSULTA_T FOR BUSCAR_TOTAL_T;
--DROP PUBLIC SYNONYM CONSULTA_UN_T FOR BUSCAR_UN_T;
--DROP PUBLIC SYNONYM LOGIN FOR COMPROBAR_LOGIN ;

CREATE PUBLIC SYNONYM CONSULTA_CT FOR PAQUETE_BUSCAR_CT ;
CREATE PUBLIC SYNONYM CONSULTA_UN_CT FOR PAQUETE_BUSCAR_UN_CT;
CREATE PUBLIC SYNONYM CONSULTA_T FOR BUSCAR_TOTAL_T;
CREATE PUBLIC SYNONYM CONSULTA_UN_T FOR BUSCAR_UN_T;
CREATE PUBLIC SYNONYM LOGIN FOR COMPROBAR_LOGIN ;

