--DISPARADOR PARA PONER ID AL TRABAJADOR
create or replace TRIGGER T_ID_Trabajador
BEFORE INSERT
ON TRABAJADOR
FOR EACH ROW
BEGIN
NEW.ID_TRABAJADOR := TRABAJADOR_ID.NEXTVAL;
END;


--DISPARADOR PARA PONER ID AL CENTRO TRABAJO
CREATE OR REPLACE TRIGGER T_ID_CT
BEFORE INSERT
ON CENTRO_TRABAJO
FOR EACH ROW
BEGIN
NEW.ID_CENTRO := CT_ID.NEXTVAL;
END;


COMMIT;