--DISPARADOR PARA PONER ID AL TRABAJADOR
create or replace TRIGGER T_ID_Trabajador
BEFORE INSERT
ON TRABAJADOR
FOR EACH ROW
BEGIN
:new.ID_TRABAJADOR := id_trabajador.NEXTVAL;
END;


--DISPARADOR PARA PONER ID AL CENTRO TRABAJO
CREATE OR REPLACE TRIGGER T_ID_CT
BEFORE INSERT
ON CENTRO_TRABAJO
FOR EACH ROW
BEGIN
:new.ID_CENTRO := ID_clave.NEXTVAL;
END;


--CUANDO SE INSERTE UN "TRABAJADOR" CREAR UN REGISTRO EN "CLAVE"
CREATE OR REPLACE TRIGGER INSERTAR_TRABAJADOR
AFTER INSERT
ON TRABAJADOR
FOR EACH ROW
BEGIN
  --INSERT INTO CLAVE VALUES (ID_CLAVE.NEXTVAL,:new.nombre,'himevico12345',SYSDATE,:new.id_trabajador);
   insertar_clave(:new.nombre, :new.id_trabajador);
END;





















--CUANDO SE INSERTE UN REGISTRO EN "CLAVE" CREAR USUARIO 


COMMIT;