/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Proyecto;

/**
 *
 * @author 7fbd12
 */
public class GestionCT extends javax.swing.JFrame {

    /**
     * @return the altaCT
     */
    public AltaCT getAltaCT() {
        return altaCT;
    }

    /**
     * @param altaCT the altaCT to set
     */
    public void setAltaCT(AltaCT altaCT) {
        this.altaCT = altaCT;
    }

    /**
     * @return the bajaCT
     */
    public BajaCT getBajaCT() {
        return bajaCT;
    }

    /**
     * @param bajaCT the bajaCT to set
     */
    public void setBajaCT(BajaCT bajaCT) {
        this.bajaCT = bajaCT;
    }

    /**
     * @return the consultarCT
     */
    public ConsultarCT getConsultarCT() {
        return consultarCT;
    }

    /**
     * @param consultarCT the consultarCT to set
     */
    public void setConsultarCT(ConsultarCT consultarCT) {
        this.consultarCT = consultarCT;
    }

    /**
     * @return the modificarCT
     */
    public ModificarCT getModificarCT() {
        return modificarCT;
    }

    /**
     * @param modificarCT the modificarCT to set
     */
    public void setModificarCT(ModificarCT modificarCT) {
        this.modificarCT = modificarCT;
    }

    /**
     * @return the pantallaAdministrador
     */
    public PantAdministrador getPantallaAdministrador() {
        return pantallaAdministrador;
    }

    /**
     * @param pantallaAdministrador the pantallaAdministrador to set
     */
    public void setPantallaAdministrador(PantAdministrador pantallaAdministrador) {
        this.pantallaAdministrador = pantallaAdministrador;
    }

    private PantAdministrador pantallaAdministrador;
    private AltaCT altaCT;
    private BajaCT bajaCT;
    private ConsultarCT consultarCT;
    private ModificarCT modificarCT;

    /**
     * Creates new form GestionTrabajadores
     */
    public GestionCT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        alta = new javax.swing.JButton();
        baja = new javax.swing.JButton();
        consulta = new javax.swing.JButton();
        modificacion = new javax.swing.JButton();

        alta.setText("Alta");
        alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaActionPerformed(evt);
            }
        });

        baja.setText("Baja");
        baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaActionPerformed(evt);
            }
        });

        consulta.setText("Consulta");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });

        modificacion.setText("Modificación");
        modificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(alta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consulta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(baja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alta)
                .addGap(18, 18, 18)
                .addComponent(baja)
                .addGap(18, 18, 18)
                .addComponent(consulta)
                .addGap(18, 18, 18)
                .addComponent(modificacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaActionPerformed
        if (altaCT == null) {
            altaCT = new AltaCT();
            altaCT.setGestionCT(this);
        }
        altaCT.setVisible(true);

    }//GEN-LAST:event_altaActionPerformed

    private void bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaActionPerformed
       if (bajaCT == null) {
            bajaCT = new BajaCT();
            bajaCT.setGestionCT(this);
        }
        bajaCT.setVisible(true);
    }//GEN-LAST:event_bajaActionPerformed

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        if (consultarCT == null) {
            consultarCT = new ConsultarCT();
            consultarCT.setGestionCT(this);
        }
        consultarCT.setVisible(true);
    }//GEN-LAST:event_consultaActionPerformed

    private void modificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificacionActionPerformed
        if (modificarCT == null) {
            modificarCT = new ModificarCT();
            modificarCT.setGestionCT(this);
        }
        modificarCT.setVisible(true);
    }//GEN-LAST:event_modificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alta;
    private javax.swing.JButton baja;
    private javax.swing.JButton consulta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificacion;
    // End of variables declaration//GEN-END:variables
}
