/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofincurso;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLType;
import java.sql.Statement;
import java.sql.Types;
import javax.swing.JOptionPane;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author 7fbd12
 */
public class InicioSesion extends javax.swing.JFrame {

    
    public PantLogistica2 getPantallaLogistica2() {
        return pantallaLogistica2;
    }

    public void setPantallaLogistica2(PantLogistica2 pantallaLogistica2) {
        this.pantallaLogistica2 = pantallaLogistica2;
    }

    public JF_Administrador getPantallaAdministrador() {
        return pantallaAdministrador;
    }

    /**
     * @param pantallaAdministrador the pantallaAdministrador to set
     */
    public void setPantallaAdministrador(JF_Administrador pantallaAdministrador) {
        this.pantallaAdministrador = pantallaAdministrador;
    }
    /**
     * @return the inisesion
     */
    private JF_Administrador pantallaAdministrador;
    //private PantLogistica1 pantallaLogistica1;
    private PantLogistica2 pantallaLogistica2;
    public static InicioSesion inisesion;

    //La conexion global para todo el programa
    public static Connection conexion;
    public static int id_T;
    
    public void limpiarInicio() {
        nombreText.setText("");
        passwordText.setText("");
    }

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        entrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Contraseña");

        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordText, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(nombreText)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(entrar)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(entrar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed

        //Cuando meta los datos de usuario compruebe el usuario en la tabla de BD y la clave de ese usuario
        String nombre = nombreText.getText();
        String password = passwordText.getText();

        //comprobar usuario y clave en tabla Clve
        try {
            Class.forName("java.sql.DriverManager");
            conexion = DriverManager.getConnection("jdbc:oracle:thin:@10.10.10.9:1521:db12102", "system", "oracle");
            Statement sentencia = conexion.createStatement();
            CallableStatement comprobar = conexion.prepareCall("{call login(?,?,?)}");

            //Los datos del usuario para iniciar sesion
            comprobar.setString(1, String.format(nombre));
            comprobar.setString(2, String.format(password));
            // la id del trabajador
            comprobar.registerOutParameter(3, Types.NUMERIC);
            comprobar.executeUpdate();
            id_T = comprobar.getInt(3);
            
            if (comprobar.getInt(3) > 0) {
                JOptionPane.showMessageDialog(this, "Correcto");
                //cerrar conexion del sistema y damos paso al trabajador con su usuario
                conexion.close();
                Class.forName("java.sql.DriverManager");
                //Aqui pondria el usuario y contraseña del trabajador
                conexion = DriverManager.getConnection("jdbc:oracle:thin:@10.10.10.9:1521:db12102", nombre, password);
                sentencia = conexion.createStatement();

                //obtener la categoria del trabajador
                CallableStatement s = conexion.prepareCall("{call CONSULTA_UN_T(?,?)}");
                s.setInt(1, id_T);
                s.registerOutParameter(2, OracleTypes.CURSOR);
                s.executeUpdate();
                ResultSet res = (ResultSet) s.getObject(2);
                
                res.next();
                
                String adm = "ADMINISTRADOR";
                String logis = "LOGISTICA";
                String trab = res.getString(14);
                res.close();
                if (trab.equals(adm)) {
                    //Abrir pantalla Administrador
                    if (pantallaAdministrador == null) {
                        pantallaAdministrador = new JF_Administrador();
                        pantallaAdministrador.setInicioSesion(this);
                    }
                    pantallaAdministrador.setVisible(true);
                    limpiarInicio();
                    
                } else {
                    //Abrir pantalla Logistica
                    if (getPantallaLogistica2() == null) {
                        /* if (pantallaLogistica1 == null) {
                            pantallaLogistica1 = new PantLogistica1();
                            pantallaLogistica1.setInicioSesion(this);
                        }
                        pantallaLogistica1.setVisible(true);
                    } else {*/
                        setPantallaLogistica2(new PantLogistica2());
                        getPantallaLogistica2().setInicioSesion(this);
                        getPantallaLogistica2().setVisible(true);
                    }
                    getPantallaLogistica2().setVisible(true);
                    limpiarInicio();
                }
                //esconder ventana
                this.setVisible(false);
                
            } else {
                JOptionPane.showMessageDialog(this, "ERROR", "Resultado", JOptionPane.ERROR_MESSAGE);
            }
            
            comprobar.close();

            //sentencia.close();
            //conexion.close();
        } catch (ClassNotFoundException | SQLException cn) {
            cn.printStackTrace();
        }

    }//GEN-LAST:event_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
        //Crear conexion con el servidor oracle 12c

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreText;
    private javax.swing.JPasswordField passwordText;
    // End of variables declaration//GEN-END:variables
}
