-- Creación de la CABECERA DEL PAQUETE

CREATE OR REPLACE PACKAGE PK_CT IS
PROCEDURE P_CT(ID_CENTRO NUMBER);
END;

-- Creación del CUERPO DEL PAQUETE

CREATE OR REPLACE PACKAGE BODY PK_CT IS
PROCEDURE P_CT(ID_CENTRO NUMBER)
IS
  BEGIN
  DECLARE
  CURSOR C_CENTRO IS
  SELECT * FROM CENTRO_TRABAJO;
  S CENTRO_TRABAJO%ROWTYPE;
    BEGIN
      OPEN C_CENTRO;
      DBMS_OUTPUT.PUT_LINE ('ID' ||' '||'NOMBRE'||'      '||'CALLE'||'         '||'Nº');
      LOOP
      FETCH C_CENTRO INTO S;
      EXIT WHEN C_CENTRO%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE (S.ID_CENTRO ||' '||S.NOMBRE||' '||S.CALLE||' '||S.NÚMERO);
      END LOOP;
    CLOSE C_CENTRO;
    END;
  END;
END;

EXECUTE PK_CT.P_CT(0);

